version: '3.8'
services:
  frontend:
    build: ./frontend/todo
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
