name: Buddywise CI/CD

on:
 push:
   branches:
     development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install

      - name: Build Backend (Python)
        working-directory: backend
        run: |
          pip3 install -r requirements.txt
          python -m unittest discover tests

      - name: Build Docker Images
        run: |
          docker build -t buddywise-application-frontend:latest ./frontend
          docker build -t buddywise-application-backend:latest ./backend

      - name: Push Docker Images to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag buddywise-application-frontend mydockerhub/buddywise-application-frontend:${{ github.sha }}
          docker tag buddywise-application-backend mydockerhub/buddywise-application-backend:${{ github.sha }}
          docker push mydockerhub/buddywise-application-frontend:${{ github.sha }}
          docker push mydockerhub/buddywise-application-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.ref == 'refs/heads/main' && 'development' }}
    steps:
      run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            kubectl apply -f k8s/development-deployment.yaml